### ISSUE TITLE
ng-ais-menu not working

### ISSUE THREAD

**Issue by aymericaitamer** [algolia/angular-instantsearch#113]
Hi guys,

We love Algolia but we have some trouble with the angular extension :

When I switch from **ng-ais-refinement-list** to **ng-ais-menu**, I loose all my values.

Before:
```
       <ng-ais-refinement-list attribute="category" [sortBy]="['name','desc']" showMoreLabel="See more" showLessLabel="See less"
            [limit]="3" [showMoreLimit]="100"></ng-ais-refinement-list>
```

After:
```
          <ng-ais-menu attribute="category" [sortBy]="['name','desc']" showMoreLabel="See more" showLessLabel="See less"
            [limit]="3" [showMoreLimit]="100"></ng-ais-menu>
```

The div "ais-Menu" is displayed with an "ul" inside but no items (no li).

**Comment by samouss** [comment]
I didn't manage to reproduce the error. Could you provide an example of the issue? It will help us a lot to better understand the problem. We provide template in order to avoid you the boilerplate part. You can find it on [CodeSandbox](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/Angular%20InstantSearch).

**Comment by aymericaitamer** [comment]
Thank you for the CodeSandbox, it helps me a lot.

It is now working, issued came from multiple ng-ais-refinement-list with the same attribute "category".
