### ISSUE TITLE
Is there a way to access the SearchBoxWidgetOptions on the Search Box component?

### ISSUE THREAD

**Issue by mbouclas** [algolia/angular-instantsearch#184]
specifically i'm looking for the queryHook so that i can throttle the form submission. I know there's the searchAsYouType but i'd rather throttle

**Comment by samouss** [comment]
Right now there is no built-in support for throttle the form submission. 

The `queryHook` widget params is not available in Angular InstantSearch. But you can implement your own SearchBox with the [`connectSearchBox`](https://community.algolia.com/instantsearch.js/v2/connectors/connectSearchBox.html) connector. You can either provide the `queryHook` params to the connector or implement the debounce by default since you have the control on the `refine` call. You can find [a guide](https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html) that will help you create a custom widget inside the documentation website.

**Comment by mbouclas** [comment]
the custom widget looks fine, thanks

**Comment by samouss** [comment]
I'm closing the issue, feel free to re-open a new one if needed.
