### ISSUE TITLE
Add `class` prop to every components

### ISSUE THREAD

**Issue by iam4x** [algolia/angular-instantsearch#20]
When you try to style a specific widget you have to wrap it into a div with a classname. It would be easier to have `class` property applied to the widget.

**Comment by iam4x** [comment]
I'm thinking it might be even better to have a mapping possible, like for InstantSearch.js since we do not provide a way to customize the markup yet. What do you think? (cc @vvo)

**Comment by Haroenv** [comment]
that should solve the framework interop best, since bootstrap etc. rely on specific classes on certain elements

**Comment by vvo** [comment]
I am always hesitant on those css classes feature requests because ultimately, a better option would be to have angular-instantsearch-bootstrap (all the views, using bootstrap specific classes and markup). Since we always have hit a wall with customising only the CSS class names, at some point bootstrap required some dom tree that was really different.

I know also that for react-instantsearch we never did it, because in IS.js, implementation wise it was really a lot of boilerplate code. And we said that if you already had a nice search box, then connectors would be the best.

Do you already have the concept of customization through connectors, in some way?

What's your take, also cc @ment0sman, would [connectors](https://community.algolia.com/instantsearch.js/v2/guides/customization.html) be better suited you think?

**Comment by iam4x** [comment]
We do not have the customization through connectors, because you cannot access the internal instantsearch instance with `angular-instantsearch`

I am thinking of an API for exposing the either [BaseWidget](https://github.com/algolia/angular-instantsearch/blob/master/src/base-widget.ts) class or something for the users in order to create custom widgets.

**Comment by iam4x** [comment]
The new release of the library (beta8) includes a way to write your custom widgets easily, the guide is available [in the documentation here](https://algolia.gitbooks.io/angular-instantsearch/content/custom-widgets.html).

This should solve also the issue with integrating into a CSS framework, like Bootstrap.
