### ISSUE TITLE
Guide: Configure widget is not working as expected, change of search parameter has no impact on search result

### ISSUE THREAD

**Issue by tahminabs23** [algolia/angular-instantsearch#230]
According to documentation - "any of the searchParameters added to this widget will be forwarded to Algolia".

But if I dynamically change the searchParameters, it has no impact on the search result.  

Example, https://codesandbox.io/s/kxqxr0j45r

Here, there is a button named "Update Search Parameter", and when you click on that button, it changes the search parameter. But it has no impact on the search result.

Related Issue: #92

**Comment by Haroenv** [comment]
I found the cause (phew, had to dig deep into Angular for that one). The reason is twofold:

1. we were getting `isFirstChange`, but it's a function which returns a boolean, not a boolean prop
2. regular `ngOnChange` does reference equality, but we need to do deep equality. 

Deep equality is done with a differ, which I implemented in #231

**Comment by Haroenv** [comment]
I've merged this PR, will release it soon
