### ISSUE TITLE
Importing Angular InstantSearch breaks existing HTTP requests

### ISSUE THREAD

**Issue by codebubb** [algolia/angular-instantsearch#246]
Hi all,

I have successfully implemented the Angular integration into our current app - all is working fine.  I have an issue however that any (non-Algolia) HTTP requests within the app are now failing as the app is now longer sending the JWT token (added via an Interceptor).

I believe this is down to the fact that our app already imports the HTTPClientModule to make these requests.  I found that the InstantSearch module also includes the same module (https://github.com/algolia/angular-instantsearch/blob/develop/src/instantsearch/instantsearch.module.ts) which i narrowed down to be the source of the problem.

I cloned the angular-instantsearch repo and removed the HTTPClientModule import, rebuilt and imported this modified version to our app and all is well - app specific HTTP requests work OK and so does the Aloglia lookup.

In order for us to stay current with updates ideally we don't want to continue using this modified version locally.  Therefore would it be possible to conditionally check for HTTPClientModule and only import it if it has not already been loaded by the parent app?

Thanks.

**Comment by Haroenv** [comment]
Hey @codebubb, thanks for this research. Is this something you want to do a pull request for?

**Comment by codebubb** [comment]
@Haroenv Sure, I have been looking at it this afternoon to be honest but couldn't come up with a decent solution as of yet.  Do you know if the HTTPClientModule is actually used anywhere inside the Angular-Instantsearch library? It doesn't seem obvious where it is used. Thanks.

**Comment by Haroenv** [comment]
I know it's used for server side rendering, but I'm not completely sure what it was necessary for (I'm not the main maintainer for this repo)

**Comment by iam4x** [comment]
Hi @codebubb 👋 

The HTTPClientModule is not used but we need to reference it in order to compile with AOT the library. (But maybe this has changed, if you can compile without errors might not be needed anymore).

It is only referenced in order to make SSR works when you use `createSSRSearchClient()` utility.

Even if you are not doing SSR, can you try to use `createSSRSearchClient` and provide your HTTPClientModule modified with the JWT token, see: https://github.com/algolia/angular-instantsearch/blob/69cf2884512b59ca11d867183bac138b4190bbd5/examples/server-side-rendering/src/app/app.component.ts#L79-L91

If you are willing to do a PR, remove the reference and please test the SSR example (`$ npm run examples:ssr`)

Hope this helps 👍

**Comment by codebubb** [comment]
Hi @iam4x :wave:

Thanks so much for your feedback and help.

I've created a PR to remove the reference. In summary I have:
  - Removed the reference to HttpClientModule in the InstantSearchModule
  - Built the SSR example - OK
  - Built the other examples - OK
  - Ran test suite - OK

Obviously I don't want to break the Angular integration for others so any further investigation / testing you can provide is appreciated.  

Thanks.

**Comment by iam4x** [comment]
Your welcome, thanks for the PR 🏅
