### ISSUE TITLE
NumericMenu should behaves like a radio not like a checkbox

### ISSUE THREAD

**Issue by samouss** [algolia/angular-instantsearch#407]
**Describe the bug 🐛**

The `NumericMenu` widget is implemented with `radio` elements but it behaves like a `checkbox`. We are not supposed to be able to remove a `radio` element. To remove the refinement the end user should click on the "All" option.

**Actual**

![before](https://user-images.githubusercontent.com/6513513/50282690-ea3a5980-0453-11e9-9991-7bc497b2ba19.gif)

**Should be**

![after](https://user-images.githubusercontent.com/6513513/50282699-ee667700-0453-11e9-8645-4ad60a9a6840.gif)

**Comment by tkrugg** [comment]
This appears to be the bahviour on InstantSearch.js as well.
https://instantsearchjs.netlify.com/stories/?path=/story/numericmenu--default

It looks like this behaviour originates from the connector:
https://github.com/algolia/instantsearch.js/blob/develop/src/connectors/numeric-menu/connectNumericMenu.js#L313

However both vue and react don't have it.
- For Vue, the reason is `refine` is bound to `change` event, which does not fire on second click.
- For React, it appears that the connector does not have the same behaviour as the vanilla's

**Comment by tkrugg** [comment]
fixed by @yannickcr in #501
