### ISSUE TITLE
Algolia Angular Universar - NullInjectorError: No provider for request!

### ISSUE THREAD

**Issue by j34nt** [algolia/angular-instantsearch#628]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is: run algolia Angular Instantsearch on Angular Universal, i follow the documentation
https://community.algolia.com/angular-instantsearch/guides/server-side-rendering.html, but throw me the error
Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[request]: 
  StaticInjectorError(Platform: core)[request]: 
    NullInjectorError: No provider for request!
NullInjectorError: StaticInjectorError(AppModule)[request]: 
  StaticInjectorError(Platform: core)[request]: 
    NullInjectorError: No provider for request!

I have the home component in a module outside from app.module, the search component its on Shared module.

**Comment by samouss** [comment]
Thanks for the issue! Could you provide a bit more context about the problem? Which version of Angular InstantSearch is used? Which version of Angular Universal is used? The best is always a reproducible example of the issue, it would help to better understand where the problem comes from. We provide a template to avoid you the boilerplate part. You can find it on [CodeSandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch).

**Comment by j34nt** [comment]
yeah sorry...
Angular 8
Angular universal
angular-instantsearch 2.2.2

search.component
const req = isPlatformBrowser(this.platformId) ? this.injector.get('request'); : undefined

server.ts
app.engine('html', (_, options, callback) => {
  const engine = ngExpressEngine({
    bootstrap: AppServerModuleNgFactory,
    providers: [
      { provide: 'request', useFactory: () => options.req, deps: [] },
      provideModuleMap(LAZY_MODULE_MAP)
    ]
  });
  engine(_, options, callback);
});

**Comment by tkrugg** [comment]
Thanks @j34nt, I'll have a look and get back at you.

**Comment by tkrugg** [comment]
Hey again @j34nt 
I've been looking into Angular 8 compat and updated our SSR example (see https://github.com/algolia/angular-instantsearch/issues/599) to check everything is still working.

There is one obvious thing that we need to do: allow `@angular/...@8` in peer dependencies in order to be able to use angular-instantsearch with Angular 8. Gets rid of the warnings, but a non blocker. 

However I haven't reproduced your problem, it would helpful to look at your code. Could you send us a just enough code to showcase the issue?

**Comment by tkrugg** [comment]
Hi @j34nt. I'll close this issue for now but feel free to reopen it if you want to discuss it furthermore.
