### ISSUE TITLE
<ais-instantsearch> has BUG that affect the Router

### ISSUE THREAD

**Issue by Hishmad** [algolia/angular-instantsearch#729]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is: -- PLEASE FILL IN HERE --

When using <ais-instantsearch>, it changes the normal behavior for the Router, for instance, when navigating from parent component to child component, then we need to click the back button twice in order to return to the parent component, and also some other wired behaviour related to the Router.

Any solution?
Regards
Hishmad

**Comment by Haroenv** [comment]
This happens when the way you're navigating to the other page, and that already adds an entry to history automatically. We also clear the url on `dispose` (teardown) of the InstantSearch component.

The way to solve this is by customising the `router` (part of `routing`). This can be exactly the same as the existing historyRouter (code is in InstantSearch.js), except on `dispose` you _don't_ write the url.

Hope that helps!

**Comment by Hishmad** [comment]
Thank you
