### ISSUE TITLE
Must refresh the browser to get new update??

### ISSUE THREAD

**Issue by Hishmad** [algolia/angular-instantsearch#733]
Hi

Is this normal behaviour for the user must refresh the browser every time they want to get a new update from Algolia index? is there a way to make it reactive, so the user doesn't have to refresh the browser?

**Comment by francoischalifour** [comment]
Hey, I assume you're updating your index and expect the search results to update in real time based on this new data. By default, you won't see the new data because the underlying search client caches the search requests to returned the cached results for speed reasons.

However, you can either [programmatically clears the InstantSearch cache](https://www.algolia.com/doc/guides/building-search-ui/going-further/improve-performance/angular/#refresh-the-cache-triggered-by-an-action-from-the-user), or decide to [not cache results](https://www.algolia.com/doc/api-client/advanced/configure-the-client/javascript/?language=javascript#cache-on-requests-and-responses).
