### ISSUE TITLE
TS7016: Could not find a declaration file for module 'algoliasearch/lite'

### ISSUE THREAD

**Issue by Karman40** [algolia/angular-instantsearch#803]
```
    "algoliasearch": "^3.35.1",
    "angular-instantsearch": "^3.0.0-beta.5",
    "instantsearch.js": "^4.11.0",
```

Config:
```
  private algoliaClient = algoliasearch(environment.algolia.app_id, environment.algolia.public_key);
  public algoliaConfig = {
    indexName: environment.algolia.includes.pofiles,
    searchClient: this.algoliaClient,
    routing: true,
  };
```

![image](https://user-images.githubusercontent.com/32225709/104653187-84fcd500-56ba-11eb-8472-7d3196949d28.png)
![image](https://user-images.githubusercontent.com/32225709/104653230-8f1ed380-56ba-11eb-973f-d44cf8bf771a.png)

After install @types/algoliasearch:
![image](https://user-images.githubusercontent.com/32225709/104653320-b83f6400-56ba-11eb-9361-908c93f03f72.png)

**Comment by Haroenv** [comment]
The types of searchClient seem to not match properly indeed, but unfortunately I can't see a way to make this fit again in typescript strict mode. 

The only alternative I see is using `as any` for now. In the in-progress v4 this is fixed by declaring the type in a different way (but that's not possible in v3, because it comes from upstream InstantSearch)

Here's a GitHub repo showing how to use this workaround: https://github.com/Haroenv/angular-instantsearch-test-ts

**Comment by Karman40** [comment]
@Haroenv  So I downgraded to `instantsearch.js@4` to `instantsearch.js@3` and installed:


- `"@types/algoliasearch": "^3.34.11"`
- `"@types/algoliasearch-helper": "^2.26.1"`
- `"@types/events": "^3.0.0"`

So now it works fine thank you. Although it is very tangled and opaque for me when and what I need to install to make it work.
Thank you for your help!

**Comment by Haroenv** [comment]
This is something that we will fix for sure in the next major of angular instantsearch, sorry for the inconvenience for the time being
